import {lazy,Suspense,useState} from 'react';import SiteShell from '../components/SiteShell';import DailyTrivia from '../components/DailyTrivia';import DailyGame from '../components/DailyGame';import {triviaBank} from '../data/trivia';const HeroInfinityRun=lazy(()=>import('../games/HeroInfinityRun'));const PortalDefender=lazy(()=>import('../games/PortalDefender'));const MultiverseCollector=lazy(()=>import('../games/MultiverseCollector'));import {articles} from '../data/articles'
export function DailyPage(){return <SiteShell><header className="page-title"><p className="kicker">IST DAILY ROTATION</p><h1>Daily Challenge</h1><p>The same challenge appears worldwide for each Indian calendar date.</p></header><div className="card-grid"><DailyTrivia/><DailyGame/></div></SiteShell>}
export function TriviaPage(){const[category,setCategory]=useState('All'),[difficulty,setDifficulty]=useState('All');const cats=['All',...new Set(triviaBank.map(q=>q.category))];const items=triviaBank.filter(q=>(category==='All'||q.category===category)&&(difficulty==='All'||q.difficulty===difficulty));return <SiteShell><header className="page-title"><h1>Trivia Archive</h1><p>{triviaBank.length} source-reviewed questions. MCU/film confirmations and comic context are labelled separately.</p></header><div className="filters"><label>Category <select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></label><label>Difficulty <select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['All','easy','medium','hard'].map(c=><option key={c}>{c}</option>)}</select></label></div>{items.map(q=><DailyTrivia key={q.id} question={q}/>)}</SiteShell>}
export function GamesPage(){return <SiteShell><header className="page-title"><h1>Games</h1><p>Three original, keyboard-and-touch playable modes. Scores stay on your device.</p></header><Suspense fallback={<p>Loading game modules…</p>}><div className="card-grid"><HeroInfinityRun/><PortalDefender/><MultiverseCollector/></div></Suspense></SiteShell>}
export function ArticlesPage(){const[category,setCategory]=useState("All"),categories=["All",...new Set(articles.map(a=>a.category))];return <SiteShell><header className="page-title"><h1>Articles</h1><p>Original, spoiler-conscious explainers with visible source lists.</p></header><div className="filters"><label>Category <select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="article-grid">{articles.filter(a=>category==="All"||a.category===category).map(a=><article className="content-card" key={a.slug}><p className="kicker">{a.label} · {a.category}</p><h2><a href={`/articles/${a.slug}/`}>{a.title}</a></h2><p>{a.description}</p><small>{a.minutes} min read · Updated {a.updated}</small></article>)}</div></SiteShell>}
export function ArticlePage({slug}:{slug:string}){const a=articles.find(x=>x.slug===slug);if(!a)return <NotFound/>;return <SiteShell><article className="longform"><nav aria-label="Breadcrumb"><a href="/articles/">Articles</a> / {a.title}</nav><p className="kicker">{a.label} · {a.category}</p><h1>{a.title}</h1><p className="dek">{a.description}</p><p>By {a.author} · Published {a.published} · Updated {a.updated} · {a.minutes} min read</p>{a.spoiler&&<aside><strong>Spoiler warning:</strong> This article discusses story outcomes.</aside>}{a.label==="theory"&&<aside><strong>Speculation notice:</strong> This theory is not confirmed and uses no leaks.</aside>}<aside>Editorial note: AI may assist drafting, but factual content requires human review before publication. No leaks are used.</aside>{a.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2><p>{s.body}</p></section>)}<h2>Sources</h2>{a.sources.length?<ul>{a.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title} ↗</a></li>)}</ul>:<p>This site-process article describes original functionality and makes no external film claim.</p>}<h2>Related articles</h2><ul>{articles.filter(x=>x.slug!==a.slug).slice(0,3).map(x=><li key={x.slug}><a href={`/articles/${x.slug}/`}>{x.title}</a></li>)}</ul></article></SiteShell>}
export function NotFound(){return <SiteShell><header className="page-title"><h1>Signal not found</h1><p>The requested route does not exist.</p><a className="primary link-button" href="/">Return home</a></header></SiteShell>}
const policy:Record<string,{title:string;body:JSX.Element}>={
'/about/':{title:'About Doomsday Daily',body:<><p>An independent countdown, trivia and fan-analysis project built for curious viewers. The cinematic countdown remains its centre.</p><p>We are not an official studio publication and never present fan analysis as production news.</p></>},
'/sources/':{title:'Sources',body:<><p>Movie-specific confirmation should trace to Marvel, Disney, a studio release, or a clearly identified participant’s direct statement. Marvel character guides and original publications support historical context.</p><p>Visible citations let readers inspect the evidence and dates. A source link supports only the claim beside it—not unrelated speculation.</p><ul><li><a href="https://www.marvel.com/movies/avengers-doomsday">Marvel’s official Avengers: Doomsday page</a></li><li><a href="https://thewaltdisneycompany.com/">The Walt Disney Company newsroom</a></li></ul></>},
'/editorial-policy/':{title:'Editorial Policy',body:<><h2>Confirmation, context and analysis</h2><p>Confirmed claims require an authoritative direct source. Comic history is labelled context. Interpretation is labelled analysis. Rumours never become facts through repetition.</p><h2>Corrections and spoilers</h2><p>We update a claim when its primary source changes, record the updated date and welcome documented corrections through the configured contact route. Spoilers receive a warning; leaks are prohibited.</p><h2>AI-assisted drafting</h2><p>AI may assist with a draft, but a human must review wording, every factual claim and every source before publication. Generated citations are not treated as verified. Fabricated claims and quotations are prohibited.</p></>},
'/privacy/':{title:'Privacy Policy',body:<><p>Last updated: 25 August 2026. No account is required. Trivia answers, scores and streaks may use localStorage and remain on your device; the experience continues if storage is blocked. The operator does not collect that data or sell personal data.</p><h2>Advertising</h2><p>The Google AdSense publisher script loads on eligible pages to support account-level Auto ads. Auto ads do not require <code>VITE_ADSENSE_SLOT</code>; that setting controls only optional manual ad units, which appear only when a valid slot is configured.</p><p>Google may process advertising, device, cookie or similar data according to its policies. Consent requirements depend on location. <a href="https://policies.google.com/technologies/partner-sites">How Google uses information from partner sites</a>.</p><h2>Analytics</h2><p>No analytics service is currently configured.</p></>},
'/contact/':{title:'Contact',body:<>{import.meta.env.VITE_CONTACT_URL?<p><a href={import.meta.env.VITE_CONTACT_URL}>Contact the editorial team</a></p>:<p>No public contact method is configured. Maintainers can set <code>VITE_CONTACT_URL</code> to a reviewed HTTPS contact form or address page; no email address has been invented.</p>}<p>For a correction, include the page, disputed wording and an authoritative source.</p></>},
}
export function TrustPage({path}:{path:string}){const page=policy[path];return <SiteShell><article className="longform"><h1>{page.title}</h1>{page.body}</article></SiteShell>}
export function UpdatesPage(){return <SiteShell><header className="page-title"><p className="kicker">AUTHORITATIVE SOURCES ONLY</p><h1>Confirmed Updates</h1><p>No newly reviewed update entries are published. This honest empty state avoids turning old or unverified claims into news.</p><p>For the current baseline, visit <a href="https://www.marvel.com/movies/avengers-doomsday">Marvel’s official movie page</a>.</p></header></SiteShell>}
